### ISSUE TITLE
Matchen der Schlüsselwörter auf Kategorie

### ISSUE THREAD

**Issue by nicolai92** [nicolai92/alexa-skill-hochschule-fulda#41]
Synonyme für die einzelnen Kategorien (Key-Value-Paare)

**Comment by nicolai92** [comment]
Fleisch matcht z.B. auf RInd, Schwein und Geflügel. Funktion, welche die 3 Kategorien zu einem Array verbindet.

**Comment by Dstemmer92** [comment]
Done
